name: Github Pages deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write  # Grants write permissions to contents

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3  # Update to the latest version of checkout
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3  # Update to the latest version of setup-node
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
        env:
          PUBLIC_BASE_PATH: /Thecyberhub.org
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4  # Use the latest version of the deploy action
        with:
          branch: gh-pages  # The branch the action should deploy to
          folder: dist  # The folder the action should deploy
          clean: true  # Ensures the branch is cleaned before deploying
          token: ${{ secrets.PAT_TOKEN }}  # Uses the GitHub token for authentication
